// Talksmiths CRM — Mock Data (Demo leads from real prospect list)
import { Lead, Contact, Activity, CRMUser, Partner } from './types';

export const DEMO_USERS: CRMUser[] = [
  { id: 'user-1', name: 'Saad', email: 'admin@talksmiths.ma', role: 'admin', avatarColor: '#6366f1' },
];

export const DEMO_LEADS: Lead[] = [
  {
    id: 'lead-1',
    companyName: 'ORA Technologies',
    sector: 'FinTech / Super-app',
    city: 'Casablanca',
    fundingStage: 'Series A ($7.5M)',
    englishRequirement: 'High — English investor relations',
    internationalPresence: 'Morocco, expanding Africa',
    score: 88,
    stage: 'discovery_call',
    dealValue: 180000,
    assignedTo: 'user-1',
    source: 'LinkedIn',
    tags: ['Hot Lead', 'CFO Contact'],
    nextFollowup: '2026-04-18',
    position: 0,
    createdAt: '2026-04-11T10:00:00Z',
    updatedAt: '2026-04-13T14:30:00Z',
  },
  {
    id: 'lead-2',
    companyName: 'Concentrix (ex-Webhelp)',
    sector: 'BPO / Customer Experience',
    city: 'Casablanca',
    fundingStage: 'Subsidiary (Concentrix)',
    englishRequirement: 'Very High — English customer support',
    internationalPresence: 'Global — serves EU, US, UK clients',
    score: 95,
    stage: 'contacted',
    dealValue: 350000,
    assignedTo: 'user-1',
    source: 'LinkedIn',
    tags: ['Enterprise', 'BPO'],
    nextFollowup: '2026-04-16',
    position: 0,
    createdAt: '2026-04-07T08:00:00Z',
    updatedAt: '2026-04-07T15:00:00Z',
  },
  {
    id: 'lead-3',
    companyName: 'Foundever (ex-Sitel)',
    sector: 'BPO / CX',
    city: 'Casablanca',
    fundingStage: 'Subsidiary (Foundever)',
    englishRequirement: 'Very High — native-level English support',
    internationalPresence: 'Global — US, EU, UK clients',
    score: 92,
    stage: 'contacted',
    dealValue: 300000,
    assignedTo: 'user-1',
    source: 'LinkedIn',
    tags: ['Enterprise', 'BPO'],
    nextFollowup: '2026-04-17',
    position: 1,
    createdAt: '2026-04-07T08:00:00Z',
    updatedAt: '2026-04-08T10:00:00Z',
  },
  {
    id: 'lead-4',
    companyName: 'Chari',
    sector: 'FinTech / B2B E-commerce',
    city: 'Casablanca',
    fundingStage: 'Series A ($12M) — YC S21',
    englishRequirement: 'Very High — international investors, Visa partner',
    internationalPresence: 'Morocco, Tunisia, Ivory Coast',
    score: 90,
    stage: 'new_lead',
    dealValue: 200000,
    assignedTo: 'user-1',
    source: 'Research',
    tags: ['Y-Combinator', 'Startup'],
    nextFollowup: '2026-04-19',
    position: 0,
    createdAt: '2026-04-10T09:00:00Z',
    updatedAt: '2026-04-10T09:00:00Z',
  },
  {
    id: 'lead-5',
    companyName: 'Infomineo',
    sector: 'Research & BPO',
    city: 'Casablanca',
    fundingStage: 'Growth (VC-backed)',
    englishRequirement: 'Very High — English-language research delivery',
    internationalPresence: 'Middle East, Europe, US',
    score: 85,
    stage: 'contacted',
    dealValue: 150000,
    assignedTo: 'user-1',
    source: 'LinkedIn',
    tags: ['Research', 'VC-backed'],
    nextFollowup: '2026-04-20',
    position: 2,
    createdAt: '2026-04-07T08:00:00Z',
    updatedAt: '2026-04-08T11:00:00Z',
  },
  {
    id: 'lead-6',
    companyName: 'Capgemini Morocco',
    sector: 'IT Consulting / Digital',
    city: 'Casablanca',
    fundingStage: 'Subsidiary (Capgemini)',
    englishRequirement: 'Very High — English project delivery',
    internationalPresence: 'Global — 50+ countries',
    score: 93,
    stage: 'new_lead',
    dealValue: 400000,
    assignedTo: 'user-1',
    source: 'Research',
    tags: ['Enterprise', 'IT Services'],
    nextFollowup: null,
    position: 1,
    createdAt: '2026-04-12T14:00:00Z',
    updatedAt: '2026-04-12T14:00:00Z',
  },
  {
    id: 'lead-7',
    companyName: 'HPS (Hightech Payment Systems)',
    sector: 'Payment Solutions',
    city: 'Casablanca',
    fundingStage: 'Listed (Casablanca Bourse)',
    englishRequirement: 'Very High — English client engagement',
    internationalPresence: '90+ countries worldwide',
    score: 91,
    stage: 'new_lead',
    dealValue: 250000,
    assignedTo: 'user-1',
    source: 'Research',
    tags: ['FinTech', 'Listed'],
    nextFollowup: null,
    position: 2,
    createdAt: '2026-04-12T14:00:00Z',
    updatedAt: '2026-04-12T14:00:00Z',
  },
  {
    id: 'lead-8',
    companyName: 'Deloitte Morocco',
    sector: 'Audit / Consulting',
    city: 'Casablanca',
    fundingStage: 'Subsidiary (Deloitte)',
    englishRequirement: 'Very High — English consulting delivery',
    internationalPresence: 'Global — Africa hub',
    score: 94,
    stage: 'new_lead',
    dealValue: 500000,
    assignedTo: 'user-1',
    source: 'Research',
    tags: ['Big 4', 'Consulting'],
    nextFollowup: null,
    position: 3,
    createdAt: '2026-04-13T09:00:00Z',
    updatedAt: '2026-04-13T09:00:00Z',
  },
  {
    id: 'lead-9',
    companyName: 'Teleperformance (ex-Majorel)',
    sector: 'BPO / CX',
    city: 'Casablanca',
    fundingStage: 'Subsidiary (Teleperformance)',
    englishRequirement: 'Very High — multilingual support incl. English',
    internationalPresence: 'Global — 30+ countries',
    score: 94,
    stage: 'contacted',
    dealValue: 400000,
    assignedTo: 'user-1',
    source: 'LinkedIn',
    tags: ['Enterprise', 'BPO'],
    nextFollowup: '2026-04-16',
    position: 3,
    createdAt: '2026-04-07T08:00:00Z',
    updatedAt: '2026-04-07T16:00:00Z',
  },
  {
    id: 'lead-10',
    companyName: 'Nuitée',
    sector: 'Travel Tech / B2B',
    city: 'Casablanca',
    fundingStage: 'Series A ($48M) — Accel-led',
    englishRequirement: 'Very High — US/EU clients, English product',
    internationalPresence: 'Global — hotel distribution worldwide',
    score: 89,
    stage: 'contacted',
    dealValue: 220000,
    assignedTo: 'user-1',
    source: 'LinkedIn',
    tags: ['Startup', 'Travel'],
    nextFollowup: '2026-04-18',
    position: 4,
    createdAt: '2026-04-08T10:00:00Z',
    updatedAt: '2026-04-08T14:00:00Z',
  },
  {
    id: 'lead-11',
    companyName: 'xHub',
    sector: 'Software Dev / Innovation',
    city: 'Casablanca',
    fundingStage: 'Growth',
    englishRequirement: 'Very High — English as primary work language',
    internationalPresence: 'Europe, US',
    score: 86,
    stage: 'contacted',
    dealValue: 120000,
    assignedTo: 'user-1',
    source: 'LinkedIn',
    tags: ['Startup', 'Software'],
    nextFollowup: '2026-04-19',
    position: 5,
    createdAt: '2026-04-08T10:00:00Z',
    updatedAt: '2026-04-08T15:00:00Z',
  },
  {
    id: 'lead-12',
    companyName: 'Accenture Morocco',
    sector: 'IT Consulting / Tech',
    city: 'Casablanca',
    fundingStage: 'Subsidiary (Accenture)',
    englishRequirement: 'Very High — English as working language',
    internationalPresence: 'Global',
    score: 96,
    stage: 'new_lead',
    dealValue: 450000,
    assignedTo: 'user-1',
    source: 'Research',
    tags: ['Enterprise', 'IT Services'],
    nextFollowup: null,
    position: 4,
    createdAt: '2026-04-08T09:00:00Z',
    updatedAt: '2026-04-08T09:00:00Z',
  },
];

export const DEMO_CONTACTS: Contact[] = [
  {
    id: 'contact-1',
    leadId: 'lead-1',
    name: 'Ibtissam TIRAFI',
    title: 'CFO',
    phone: '0676202009',
    email: 'majdaraghib895@gmail.com',
    linkedinUrl: 'https://linkedin.com/in/ibtissam-tirafi',
    isPrimary: true,
    isChampion: false,
  },
  {
    id: 'contact-2',
    leadId: 'lead-1',
    name: 'Majda Raghib',
    title: 'Key Account Manager',
    phone: '',
    email: '',
    linkedinUrl: '',
    isPrimary: false,
    isChampion: true,
  },
  {
    id: 'contact-3',
    leadId: 'lead-2',
    name: 'Youssef Hajjami',
    title: 'HR Manager',
    phone: '',
    email: '',
    linkedinUrl: 'https://linkedin.com/in/youssef-hajjami',
    isPrimary: true,
    isChampion: false,
  },
  {
    id: 'contact-4',
    leadId: 'lead-2',
    name: 'Ghita Krafess',
    title: 'Personnel & HR Director',
    phone: '',
    email: '',
    linkedinUrl: 'https://linkedin.com/in/ghitakrafess',
    isPrimary: false,
    isChampion: false,
  },
  {
    id: 'contact-5',
    leadId: 'lead-3',
    name: 'Réda Nejjar',
    title: 'HR Director',
    phone: '',
    email: '',
    linkedinUrl: '',
    isPrimary: true,
    isChampion: false,
  },
  {
    id: 'contact-6',
    leadId: 'lead-3',
    name: 'Fatna Abdouh',
    title: 'Directrice Adjointe RH',
    phone: '',
    email: '',
    linkedinUrl: 'https://linkedin.com/in/fatna-abdouh-27b2b11b',
    isPrimary: false,
    isChampion: false,
  },
  {
    id: 'contact-7',
    leadId: 'lead-4',
    name: 'Ismael Belkhayat',
    title: 'CEO',
    phone: '',
    email: '',
    linkedinUrl: '',
    isPrimary: true,
    isChampion: false,
  },
  {
    id: 'contact-8',
    leadId: 'lead-5',
    name: 'Taha Akhanchouf',
    title: 'HR Manager',
    phone: '',
    email: '',
    linkedinUrl: '',
    isPrimary: true,
    isChampion: false,
  },
  {
    id: 'contact-9',
    leadId: 'lead-9',
    name: 'Yassine El idrissi',
    title: 'Regional HR',
    phone: '',
    email: '',
    linkedinUrl: '',
    isPrimary: true,
    isChampion: false,
  },
  {
    id: 'contact-10',
    leadId: 'lead-10',
    name: 'Ali IHNOUSSA',
    title: 'People & Culture',
    phone: '',
    email: '',
    linkedinUrl: '',
    isPrimary: true,
    isChampion: false,
  },
  {
    id: 'contact-11',
    leadId: 'lead-11',
    name: 'Badr El Houari',
    title: 'CEO',
    phone: '',
    email: '',
    linkedinUrl: '',
    isPrimary: true,
    isChampion: false,
  },
  {
    id: 'contact-12',
    leadId: 'lead-12',
    name: 'Amine El Rhayour',
    title: 'HR Business Partner',
    phone: '',
    email: '',
    linkedinUrl: '',
    isPrimary: true,
    isChampion: false,
  },
];

export const DEMO_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    leadId: 'lead-1',
    userId: 'user-1',
    userName: 'Saad',
    type: 'linkedin',
    content: 'Connected with Majda Raghib (Champion) on LinkedIn. Liked her last 2 posts about ORA\'s growth.',
    createdAt: '2026-04-11T10:30:00Z',
  },
  {
    id: 'act-2',
    leadId: 'lead-1',
    userId: 'user-1',
    userName: 'Saad',
    type: 'email',
    content: 'Sent M&A-focused pitch to CFO. Mentioned Deloitte/Baker Tilly experience. Highlighted Cathedis acquisition and IPO readiness angle.',
    createdAt: '2026-04-12T09:00:00Z',
  },
  {
    id: 'act-3',
    leadId: 'lead-1',
    userId: 'user-1',
    userName: 'Saad',
    type: 'email',
    content: 'CFO responded: "Je vous propose de reprendre contact la semaine prochaine... dans nos locaux à Casablanca." Direct number provided.',
    createdAt: '2026-04-12T16:00:00Z',
  },
  {
    id: 'act-4',
    leadId: 'lead-1',
    userId: 'user-1',
    userName: 'Saad',
    type: 'call',
    content: 'Call booked for next week at Casa offices. CFO is precise on English as ROI lever for finance function. Methodology must be presented as "Industry-Calibrated" and "Personalized".',
    createdAt: '2026-04-13T14:30:00Z',
  },
  {
    id: 'act-5',
    leadId: 'lead-2',
    userId: 'user-1',
    userName: 'Saad',
    type: 'linkedin',
    content: 'Connected with Youssef Hajjami on LinkedIn. Sent personalized intro about Concentrix\'s US/UK strategic accounts.',
    createdAt: '2026-04-07T11:00:00Z',
  },
  {
    id: 'act-6',
    leadId: 'lead-2',
    userId: 'user-1',
    userName: 'Saad',
    type: 'email',
    content: 'Drafted and sent outreach email. Focus: industry-specific English training for customer support teams handling US/UK clients.',
    createdAt: '2026-04-07T15:00:00Z',
  },
  {
    id: 'act-7',
    leadId: 'lead-3',
    userId: 'user-1',
    userName: 'Saad',
    type: 'email',
    content: 'Drafted outreach for Foundever. Focus on 7-step methodology for operational English mastery.',
    createdAt: '2026-04-07T16:30:00Z',
  },
  {
    id: 'act-8',
    leadId: 'lead-9',
    userId: 'user-1',
    userName: 'Saad',
    type: 'email',
    content: 'Drafted outreach to Teleperformance (post-Majorel integration). Emphasis on premium English for global accounts.',
    createdAt: '2026-04-07T14:00:00Z',
  },
];

export const DEMO_PARTNERS: Partner[] = [];
